### PR TITLE
Add Docker compatibility

### PR DESCRIPTION
**Pull request by PRIHLOP**
Add Docker compatibility to simple and fast launch. Also add documentation about Docker.

### CODE REVIEW

**Review by MasterGroosha — COMMENTED** [review]
Hello! Thank you for this Pull Request!
First of all: I'm making some _noticeable_ changes for this bot, so I cannot accept your PR right now.

Anyway, I inspected suggested Dockerfile and would like to ask you some questions:
1) Why do you install build-essential and python-dev? 
2) Why do you install `distribute` package?
3) Why you chose `/root` directory as a working directory, since running as `root` user isn't necessary at all and may lead to security issues?

**Comment by PRIHLOP** [comment]
Hello.

Yes I agree that code must be clean and readable.
I will fix all of you noted.
Sorry I made hastily Pull request.

**Comment by PRIHLOP** [comment]
Hi.
Well.
I made changes and tested it. Can you accept my PR?

**Comment by PRIHLOP** [comment]
Sorry, I was also delete build-essential and python-dev packages as unused.

**Comment by MasterGroosha** [comment]
@PRIHLOP Thank you for your edits! Please take a look at my recent commits.
I finally pushed completely refactored code including what you pointed to me.

**Comment by PRIHLOP** [comment]
I reviewed code and made some changes.

But best practices for work with Docker is config variables in container environment.
Can you make read from environment first, and if variables is not present read it from `config.py` file?

**Comment by MasterGroosha** [comment]
@PRIHLOP Thank you for your edits. However I have some questions/issues with your PR:

1) I don't use `config.py` file anymore, but `config.ini` (uses Python [configparser](https://docs.python.org/3/library/configparser.html) from standard library). INI-files are generally more readable by non-techy humans.
2) Is `env.dist` file automatically sourced by docker-compose? If yes, what's the difference between `.env`, `.env.dist` and simply entering variables in `docker-compose.yml`?
3) Why are you trying to downgrade `docker-compose.yml` version from 3.8 to 3.7? 
4) Why are you sourcing timezone file from host? (I think I know the reason, but just to be sure)

Regarding "Can you make read from environment first, and if variables is not present read it from config.py file?"
This sounds like a great idea, however this might be not the best approach if bot is used outside of Docker (deployed on host machine via Systemd). Suggestions?

**Comment by PRIHLOP** [comment]
1. Ok, I will revert use of `config.ini` file
2. No, only `.env` file automatically sourced by docker-compose. In `.env.dist` file are variable names for use.
3. In different systems different versions have different compabilitiies, version 3.7 more stable for more distributives.
4. It is more simple and stable way to configure timezone, host time zone used as point of start time count(I tried differnet ways, but only this more simple and stable).

I do not suggest to cut config file fully, only add possibility to receive variables from environment. For example, do check variables in environment first, if not present read it from file.

**Comment by PRIHLOP** [comment]
Hi.

What do you think about my changes and answer to your questions?

**Comment by MasterGroosha** [comment]
@PRIHLOP Hello. Sorry I've been a bit busy recently.
I've tested some `.env` options and I think I'll drop `config.ini` in favor of dotenv file as you suggested, since I only have 4 options to store currently

**Comment by MasterGroosha** [comment]
Sorry it took so long!
I've finally implemented what you requested, so please review [this commit](https://github.com/MasterGroosha/telegram-report-bot/commit/4f4dfdf84607778fbd37ea9d45e6399c402ed989)

As I noted before, I'm currently using self-hosted GitLab instance to host most of my code, so I cannot merge your PR and did the same manually instead.

**Pull request closed without merging**
